const products = [
    {
        id: 1,
        name: 'Laptop Acer',
        type: 'laptop',
        brand: 'Acer',
        harga: 8000000,
    },
    {
        id: 2,
        name: 'Laptop Lenovo',
        type: 'laptop',
        brand: 'Lenovo',
        harga: 7000000,
    },
    {
        id: 3,
        name: 'kulkas 2 pintu',
        type: 'electronics',
        brand: 'electronics',
        harga: 5000000,
    },
    {
        id: 4,
        name: 'mesin cuci x24',
        type: 'electronics',
        brand: 'electronics',
        harga: 10000000,
    },
    // Tambahkan produk lainnya di sini...
    {
        id: 5,
        name: 'Laptop HP',
        type: 'laptop',
        brand: 'HP',
        harga: 7500000,
    },
    {
        id: 6,
        name: 'Smartphone Xiaomi',
        type: 'phone',
        brand: 'Xiaomi',
        harga: 3500000,
    },
    {
        id: 7,
        name: 'Laptop Dell',
        type: 'laptop',
        brand: 'Dell',
        harga: 9000000,
    },
    {
        id: 8,
        name: 'Smartphone Oppo',
        type: 'phone',
        brand: 'Oppo',
        harga: 4500000,
    },
    {
        id: 9,
        name: 'Laptop Asus',
        type: 'laptop',
        brand: 'Asus',
        harga: 8500000,
    },
    {
        id: 10,
        name: 'Smartphone Vivo',
        type: 'phone',
        brand: 'Vivo',
        harga: 4200000,
    },
    {
        id: 11,
        name: 'Laptop MSI',
        type: 'laptop',
        brand: 'MSI',
        harga: 11000000,
    },
    {
        id: 12,
        name: 'lenovo sssdf as',
        type: 'laptop',
        brand: 'lenovo',
        harga: 5500000,
    },
    {
        id: 13,
        name: 'Laptop Apple',
        type: 'laptop',
        brand: 'Apple',
        harga: 12000000,
    },
    {
        id: 14,
        name: 'Smartphone Google Pixel',
        type: 'phone',
        brand: 'Google',
        harga: 8000000,
    },
    {
        id: 15,
        name: 'Laptop Microsoft Surface',
        type: 'laptop',
        brand: 'lenovo',
        harga: 10000000,
    },
    {
        id: 16,
        name: 'Smartphone LG',
        type: 'electronics',
        brand: 'lenovo',
        harga: 4800000,
    },
    {
        id: 17,
        name: 'Laptop Razer',
        type: 'laptop',
        brand: 'Razer',
        harga: 13000000,
    },
    {
        id: 18,
        name: 'Smartphone OnePlus',
        type: 'phone',
        brand: 'electronics',
        harga: 7000000,
    },
    {
        id: 19,
        name: 'Laptop Samsung',
        type: 'laptop',
        brand: 'electronics',
        harga: 9000000,
    },
    {
        id: 20,
        name: 'Smartphone Realme',
        type: 'phone',
        brand: 'electronics',
        harga: 4000000,
    },
    {
        id: 21,
        name: 'tv Politron',
        type: 'tv',
        brand: 'electronics',
        harga: 12000000,
    },
];

export default products;
